# Fichier: makefile	pour quelques exemples de macro definitions et la cible clean

CC=/usr/bin/gcc -Wall -ansi -pedantic -O
INCLUDE=include
CPPFLAGS=-I ${INCLUDE}
LIB=lib
LDFLAGS=-L ${LIB}
SRC=src_C
OBJ=obj
BIN=bin

clean:
	rm -f tmp/* Les_comptes_rendus/*
	rm -rf Les_repertoires_traites/*
