#!/bin/sh
mpirun --hostfile host-file -c 16 ./bin/NBODY_direct --in=../data/baredisk_2048-plummer_2048.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer2048bare2048_16proc_32thread_16machine
mpirun --hostfile host-file -c 16 ./bin/NBODY_direct --in=../data/baredisk_4096-plummer_4096.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer4096bare4096_16proc_32thread_16machine
mpirun --hostfile host-file -c 16 ./bin/NBODY_direct --in=../data/baredisk_8192-plummer_8192.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer8192bare8192_16proc_32thread_16machine
mpirun --hostfile host-file -c 16 ./bin/NBODY_direct --in=../data/baredisk_16384-plummer_16384.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer16384bare16384_16proc_32thread_16machine

mpirun --hostfile host-file -c 8 ./bin/NBODY_direct --in=../data/baredisk_2048-plummer_2048.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer2048bare2048_8proc_16thread_8machine
mpirun --hostfile host-file -c 8 ./bin/NBODY_direct --in=../data/baredisk_4096-plummer_4096.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer4096bare4096_8proc_16thread_8machine
mpirun --hostfile host-file -c 8 ./bin/NBODY_direct --in=../data/baredisk_8192-plummer_8192.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer8192bare8192_8proc_16thread_8machine
mpirun --hostfile host-file -c 8 ./bin/NBODY_direct --in=../data/baredisk_16384-plummer_16384.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer16384bare16384_8proc_16thread_8machine

mpirun --hostfile host-file -c 4 ./bin/NBODY_direct --in=../data/baredisk_2048-plummer_2048.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer2048bare2048_4proc_8thread_4machine
mpirun --hostfile host-file -c 4 ./bin/NBODY_direct --in=../data/baredisk_4096-plummer_4096.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer4096bare4096_4proc_8thread_4machine
mpirun --hostfile host-file -c 4 ./bin/NBODY_direct --in=../data/baredisk_8192-plummer_8192.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer8192bare8192_4proc_8thread_4machine
mpirun --hostfile host-file -c 4 ./bin/NBODY_direct --in=../data/baredisk_16384-plummer_16384.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer16384bare16384_4proc_8thread_4machine

mpirun --hostfile host-file -c 2 ./bin/NBODY_direct --in=../data/baredisk_2048-plummer_2048.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer2048bare2048_2proc_4thread_2machine
mpirun --hostfile host-file -c 2 ./bin/NBODY_direct --in=../data/baredisk_4096-plummer_4096.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer4096bare4096_2proc_4thread_2machine
mpirun --hostfile host-file -c 2 ./bin/NBODY_direct --in=../data/baredisk_8192-plummer_8192.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer8192bare8192_2proc_4thread_2machine
mpirun --hostfile host-file -c 2 ./bin/NBODY_direct --in=../data/baredisk_16384-plummer_16384.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer16384bare16384_2proc_4thread_2machine


mpirun --hostfile host-file -c 1 ./bin/NBODY_direct --in=../data/baredisk_2048-plummer_2048.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer2048bare2048_1proc_2thread_1machine
mpirun --hostfile host-file -c 1 ./bin/NBODY_direct --in=../data/baredisk_4096-plummer_4096.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer4096bare4096_1proc_2thread_1machine
mpirun --hostfile host-file -c 1 ./bin/NBODY_direct --in=../data/baredisk_8192-plummer_8192.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer8192bare8192_1proc_2thread_1machine
mpirun --hostfile host-file -c 1 ./bin/NBODY_direct --in=../data/baredisk_16384-plummer_16384.nemo --tend=10.0 --dt=0.1 --soft=0.01  > logs/plumer16384bare16384_1proc_2thread_1machine












#mpirun --hostfile host-file -c 16 ./bin/NBODY_direct --in=../data/baredisk_131072-plummer_131072.nemo --tend=10.0 --dt=0.1 --soft=0.01  --sum $1
