#!/bin/sh


mpirun --hostfile host-file-test -c 16 ./bin/NBODY_direct --in=../data/baredisk_2048-plummer_2048.nemo --tend=2 --dt=0.1 --soft=0.01 --sum





#mpirun --hostfile host-file -c 16 ./bin/NBODY_direct --in=../data/baredisk_131072-plummer_131072.nemo --tend=10.0 --dt=0.1 --soft=0.01  --sum $1
